# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171208_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='created_date',
            new_name='datacracao',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='published_date',
            new_name='datapulicacao',
        ),
    ]
