# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171208_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
