# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preco',
        ),
    ]
