# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
